image: python:3.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  - key:
      files:
        - install/requirements.txt
    paths:
      - .cache/pip
      - venv/

before_script:
  - pip install --upgrade pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install setuptools
  - pip install -r requirements-dev.txt
  - pip install .

package-test-pypi:
  stage: package
  needs:
    - test-pip
  script:
    - python setup.py sdist
    - twine upload dist/*
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
