repos:
    - repo: local
      hooks:
          - id: forbidden-files
            name: forbidden files
            entry: found copier update rejection files; please review
            language: fail
            files: "\\.rej$"
