name: PyPI Upload
concurrency: dev
run-name: Uploading version ... to PyPI
on: [push]

env:
  TWINE_REPOSITORY: ${{ vars.TWINE_REPOSITORY }}
  TWINE_USERNAME: ${{ vars.TWINE_USERNAME }}

jobs:
  testpypi-upload:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.14"
      - run: pip install --upgrade pip
      - run: pip install virtualenv
      - run: virtualenv venv
      - run: source venv/bin/activate
      - run: pip install setuptools
      - run: pip install -r requirements.txt
      - run: pip install .
      - run: python setup.py sdist
      - run: echo ${{ github.ref }}
      - run: echo $TWINE_REPOSITORY
      - run: twine upload --verbose dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

  pypi-upload:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.14"
      - run: pip install --upgrade pip
      - run: pip install virtualenv
      - run: virtualenv venv
      - run: source venv/bin/activate
      - run: pip install setuptools
      - run: pip install -r requirements.txt
      - run: pip install .
      - run: python setup.py sdist
      - run: echo ${{ github.ref }}
      - run: echo $TWINE_REPOSITORY
      - run: twine upload --verbose dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}



# script:
#     - python setup.py sdist
#     - twine upload dist/*
#   rules:
#     - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
